name: LoreAttributesREVIVE
main: Test.LoreAttributes
version: 1.3.0
description: Apply stats to weapons and armor!
author: Nighteyes604+LordPhrozen
softdepend:
commands:
  hp:
    description: Display health of yourself.
  lorestats:
    description: Display the stat benefits of your lore.