# Default Configuration #

Config:
  Debug: false
  Default-Cooldown: 0
  Default-Kit-Limit: 0
  Default-Price: 0
  New-Player-Kit: starter
  Sign-Action: view

Messages:
  Permission-Denied: '&4You do not have permission!'
  Kit-Created: '&2%K created successfully!'
  Kit-Deleted: '&2%K removed successfully!'
  Kit-Obtained: '&2%K has been added to inventory!'
  Kit-Sent: '&2You gave %K to %P!'
  Kit-Received: '&2You recieved %K from %P!'
  Kit-Exist: '&4%K already exists!'
  Kit-Not-Exist: '&4%K does not exist!'
  Get-Kit-Limit: '&4%K can only be obtained %L times! Youve reached the limit!'
  Set-Kit-Limit: '&2Limit set for %K!'
  Reset-Kit-Limit: '&2%Ps Limit Reset for %K!'
  Get-Cooldown: '&4You must wait %T before you can use this %K again!'
  Set-Cooldown: '&2Cooldown set for %K!'
  Reset-Cooldown: '&2%Ps Cooldown Reset for %K!'
  Get-Price: '&2Charged $%M'
  Set-Price: '&2Set price for %K to %M!'
  Insufficient-Funds: '&4You need at least $%M to purchase this %K!' 
  Inventory-Space: '&4Insufficient inventory space!'
  New-Player-Kit: '&2Heres a kit to get you started!'
  Kit-Book-Full: '&5There are more kits than can fit in the book. Use /kit list!'
  Not-Player: '&4You must be a player to run this command!'
  No-Player: '&4Player is offline or does not exist!'
  Invalid-Number: '&4Invalid number format!'
  Invalid-Argument: '&4Invalid argument!'
  DB-Fail: '&4Unable to connect to database!'
